### ISSUE TITLE
OpenTasks

### ISSUE THREAD

**Issue by smnthermes** [39aldo39/DecSyncCC#18]
This app has the necessary permission for OpenTasks. However, it doesn't add a "tasks" subfolder in the "DecSync" folder, nor an account on the OpenTasks app.

**Comment by 39aldo39** [comment]
I didn't know about OpenTasks. I will consider adding support for it.

**Comment by tonyk69** [comment]
I also noticed the exact same thing. Permission can be granted to the app for it, but OpenTasks does not show it as a tasks provider inside the app at all.

**Comment by teklabania** [comment]
+1 for OpenTasks support.

**Comment by naruciakk** [comment]
The option to add DecSync calendar to OpenTasks would be much appreciated, because as far as I know this is the best open source task management app on Android (and personally, this is the last thing I'm forced to sync not locally, but via a web server ;))

**Comment by Torenga** [comment]
> The option to add DecSync calendar to OpenTasks would be much appreciated, because as far as I know this is the best open source task management app on Android (and personally, this is the last thing I'm forced to sync not locally, but via a web server ;))

IMO Tasks.org is better in almost every way and where it's lagging behind the very active developer have the missing/extra features on the roadmap. OpenTasks is seemingly an unpaid side project for a professional company so it rarely gets the love it needs.

But +1 for supporting either.

**Comment by renyuneyun** [comment]
Since OpenTasks supports syncthing through CalDAV, maybe DecSyncCC can add a support of that?
Or probably through some companion apps (which I have no idea).

I also found an app called EteSync which relies on a central server and integrates with OpenTasks. Maybe DecSync can so something similar?

**Comment by kannes** [comment]
I just lost* all my TODOs in a mismatch between migration, expectation and volatile caching because I falsely expected decsync's calendar sync to include them. Because I learned my lesson and realised how much this feature would have saved me, I offer you a **100€ bounty for this** (mail me at username at enjoys dot it).

I have no clue how Android's weird and complex system stacks these things. All I want is to be able to have decsync on my phone, providing tasks/TODOs via a calendar (I guess that's how it works?!) in a standardized way and me being able to point opentasks or tasks.org at it. If they are working differently, opentasks support please. If it is a decsync, not a decsync-cc issue, please just shout and I will post over there.

*(Recovering from a hundred half complete .ics shards from a photorec session on my old radicale server snapshot is a crap job but looking good 4 hours in far...)

**Comment by 39aldo39** [comment]
Whoa, thanks for the offer! I will definitely look at implementing it quicker!

But it would also be helpful to know your situation a bit more specific, and what you did exactly. Apparently you had a false expectation somewhere, and it would be good to know how it occurred, so that the feedback of the app could be improved. If the app made clear it couldn't process to todos, you wouldn't have been in this situation either.

**Comment by kannes** [comment]
Yay!

Oh it's complicated and definitely not an issue of your app. More of the general conceptual mess that is Tasks/TODOs and how Android hides where things are actually stored. I had no idea where this was stored on the phone and had some component (I used Radicale on a server and DAVx5+OpenTasks on the phone) apparently cache my tasks, even when no syncing was occuring for them anymore. Only when I had deleted the server and then only after also uninstalled DAVx5 everything was gone.

One hint that _might_ have saved me would have been a display of "Events: xxx, Todos: ..., whateverelse: xxx" in the decsync Entries count. But I imagine there are way too many possible kinds of data things in the standard for a list of that to make sense (especially if they are not supported yet, afterwards maybe!).

**Comment by 39aldo39** [comment]
Support for tasks is implemented now! The new version should appear on F-Drdoid in a few days. As DecSync CC uses a library provided by Davx5 (ical4android) for the calendars, I didn't have to worry about most technical parts and made the implementation easier. Currently only OpenTasks is supported. Although tasks.org can easily be added, it looks like that app has a whitelist with only Davx5 and Etesync on it, so I would have to look further into that.
